databases:
  - name: members_only
    databaseName: members_only
    user: odilsonjs

services:
  - type: web
    name: members_only
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: members_only
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false